name: CI
on:
  push:
    tags:
      - v*
  pull_request:
    branches:
      - main

jobs:
  flutter_test:
    name: Run flutter test and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1.4.0
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter test

  build:
    name: Build Apps
    needs: [flutter_test]
    runs-on: macos-latest
    steps:
      - name: Export Release Timestamp
        run: echo "::set-env name=APP_VERSION::release_$(date +'%Y-%m-%d_%H-%m-%S')"
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - name: Set up Flutter
        uses: subosito/flutter-action@v1.4.0
        with:
          channel: "stable"
      - name: Install pub Dependencies
        run: flutter pub get
      - name: Build Android App
        run: flutter build apk --split-per-abi
      - name: Build iOS App
        run: |
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload
      - name: Release Apps
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.TOKEN }}
          artifacts: "build/app/outputs/apk/release/*.apk,build/ios/iphoneos/app.ipa"